#!/usr/bin/python
#
# gphotoframe - Photo Frame for the GNOME Desktop.
# 
# Copyright (c) 2009, Yoshizumi Endo.
# Licence: GPL3

from twisted.internet import gtk2reactor
gtk2reactor.install()
from twisted.internet import reactor

try:
    from gphotoframe.photoliststore import PhotoListStore
except:
    from lib.photoliststore import PhotoListStore

VERSION = 0.1

if __name__ == "__main__":
    PhotoListStore()
    reactor.run()
