#!/usr/bin/python
#
# gphotoframe - Photo Frame for the GNOME Desktop.
#
# Copyright (c) 2009-2011, Yoshizumi Endo.
# Licence: GPL3

import os
import platform
from os.path import join, abspath, dirname

from twisted.internet import gtk2reactor, glib2reactor
dist, ver = platform.dist()[:2]
greactor = glib2reactor if dist == 'Ubuntu' and float(ver) >= 10.10 \
    else gtk2reactor
greactor.install()

from twisted.internet import reactor

if os.access(
    abspath(join(dirname(__file__), 'lib/liststore.py')), os.R_OK):
    from lib.liststore import PhotoListStore
else:
    from gphotoframe.liststore import PhotoListStore

if __name__ == '__main__':
    PhotoListStore()
    reactor.run()
